# roles/ansible-role-arch-base/tasks/main.yml
---

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: ansible-role-arch-base_packages
  tags: ansible-role-arch-base

- name: Ensure service is started
  service:
    name: "{{ ansible-role-arch-base_service }}"
    state: started
    enabled: true
  tags: ansible-role-arch-base
